### ISSUE TITLE
Aspects from preprint feedback

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/paper-remodnav#7]
- data recording requirements (e.g. sampling rate): https://twitter.com/LewisChuang/status/1122450508067823616
- eye blink detection: https://twitter.com/ZSjoerds/status/1122216533470666753

Unrelated, but relevant:

- how to avoid PNG figured, maybe even plot all data points across all runs and participants: https://twitter.com/michaelwaskom/status/1123285448128901120

**Comment by adswa** [comment]
I added the ``rasterized`` parameter to the mainsequence plotting in ad6b5c647bc0781f570c2c666ea8147ac5675c3c, and it really speeds up rendering, pretty much regardless of the amount of data (only one run or all). When taking all runs in, the content of the figure changes only in the sense that the main sequence looks "fatter"/more overcrowded and the events plotted on top (saccades) superimpose the PSOs more -- thats a bit of an anti-feature. IMO we'd be fine going with only one run.

**Comment by ElectronicTeaCup** [comment]
What other data recording requirements are there for eye scanners exactly? For sampling rate, we've mentioned that there is no set default, and the sampling rates in the two data sets (good quality vs lower quality)— do we need to add anything else?

**Comment by mih** [comment]
Added some bits
